---
- name: Check if kubectl is already installed
  stat:
    path: /usr/local/bin/kubectl
  register: kubectl_bin

- name: Download kubectl
  shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod +x kubectl
    sudo mv kubectl /usr/local/bin/
    sudo chown root:root /usr/local/bin/kubectl
    sudo chmod +x /usr/local/bin/kubectl
  when: not kubectl_bin.stat.exists
  failed_when: false

- name: Verify kubectl installation
  shell: |
    export PATH="/usr/local/bin:$PATH"
    kubectl version --client --short
  register: kubectl_verify
  failed_when: false 