---
- name: Install Python 3
  apt:
    name: python3
    state: present
    update_cache: yes
  ignore_errors: yes

- name: Install pip
  apt:
    name: python3-pip
    state: present
    update_cache: yes
  ignore_errors: yes 