---
- name: Download Kind to temporary location
  get_url:
    url: https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
    dest: /tmp/kind
    mode: '0755'
  become: yes
  ignore_errors: yes

- name: Move Kind to /usr/local/bin
  copy:
    src: /tmp/kind
    dest: /usr/local/bin/kind
    mode: '0755'
    owner: root
    group: root
    remote_src: yes
  become: yes
  ignore_errors: yes

- name: Clean up temporary file
  file:
    path: /tmp/kind
    state: absent
  become: yes
  ignore_errors: yes 