---
- name: Install Docker dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  ignore_errors: yes

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  ignore_errors: yes

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  ignore_errors: yes

- name: Install Docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  ignore_errors: yes

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  ignore_errors: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  ignore_errors: yes 