- name: Ensure Python 3 is installed
  apt:
    name: python3
    state: present
    update_cache: yes
  become: yes

- name: Ensure pip for Python 3 is installed
  apt:
    name: python3-pip
    state: present
    update_cache: yes
  become: yes

- name: Ensure Java (OpenJDK 17) is installed
  apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes
  become: yes

- name: Ensure Docker is installed
  apt:
    name: docker.io
    state: present
    update_cache: yes
  become: yes

- name: Ensure user is in docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: yes

- name: Ensure kind is installed
  stat:
    path: /usr/local/bin/kind
  register: kind_bin

- name: Download kind if not present
  get_url:
    url: https://kind.sigs.k8s.io/dl/v0.23.0/kind-linux-amd64
    dest: /usr/local/bin/kind
    mode: '0755'
  become: yes
  when: not kind_bin.stat.exists

- name: Ensure kubectl is installed
  stat:
    path: /usr/local/bin/kubectl
  register: kubectl_bin

- name: Download kubectl if not present
  shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod +x kubectl
    mv kubectl /usr/local/bin/
  args:
    creates: /usr/local/bin/kubectl
  become: yes
  when: not kubectl_bin.stat.exists

- name: Ensure git is installed
  apt:
    name: git
    state: present
    update_cache: yes
  become: yes

- name: Ensure jenkins_home exists and is writable
  file:
    path: "{{ playbook_dir }}/../jenkins_home"
    state: directory
    mode: '0777'
  become: yes 